json.id product.id
json.product_number product.product_number
json.name product.name
json.categories product.categories
json.subtotal product.price
json.tax product.tax
json.total product.total
json.is_discounted? product.is_discounted?
json.images product.all_images
json.description product.description
json.supplier product.supplier.name
json.created_at product.friendly_created_at